#!/usr/bin/env ruby
# frozen_string_literal: true

require 'racli'
Bundler.require

config_params, request_params = Racli::OptionParser.new.call(ARGV)

cli = Racli::CLI.new(**config_params)
cli.call(**request_params)
